Repository vmware/terraform-provider-vmc, pull requests merged in 2020-06, with the labels that each got.

#35 Added validation for multiAZ SDDC
  go.sum
  vmc/constants.go
  vmc/resource_vmc_sddc.go
Labels: enhancement, size/M

#38 Added example and description for stretched clusters.
  examples/stretched_cluster/README.md
  examples/stretched_cluster/main.tf
  examples/stretched_cluster/variables.tf
Labels: documentation, size/L

#39 Added code to store num_host in resourceSddcRead method
  vmc/resource_vmc_sddc.go
Labels: bug, size/XS

#42 Added support for i3en host instance type
  vmc/constants.go
  vmc/resource_vmc_cluster.go
  vmc/resource_vmc_public_ip.go
  vmc/resource_vmc_sddc.go
  website/docs/r/cluster.html.markdown
  website/docs/r/sddc.html.markdown
Labels: documentation, enhancement, size/M

#41 Update the latest dependency and test the function
  go.mod
  go.sum
Labels: size/M
