Repository vmware/terraform-provider-vmc, pull requests merged in 2020-03, with the labels that each got.

#2 Updated version and contents of changelog.MD
  CHANGELOG.md
Labels: size/XS

#4 Updated instructions in README to outline steps for using released VMC provider.
  README.md
Labels: documentation, enhancement, size/M

#5 Added condition in resource update for host_instance_type
  examples/main.tf
  examples/variables.tf
  vmc/constants.go
  vmc/resource_vmc_sddc.go
  website/docs/r/sddc.html.markdown
Labels: bug, documentation, size/M

#7 Changed default number of hosts value to 1 in variables.tf file
  examples/main.tf
  examples/variables.tf
Labels: size/XS

#11 Fix for re-creating public IP if it is accidentally delete via console
  vmc/resource_vmc_public_ip.go
Labels: size/XS

#10 Updated variables.tf for description of fields.
  examples/variables.tf
  website/docs/index.html.markdown
  website/docs/r/sddc.html.markdown
Labels: documentation, size/S

#12 Updated documentation.
  examples/variables.tf
  website/docs/r/sddc.html.markdown
Labels: documentation, size/XS
