Repository vmware/terraform-provider-vmc, pull requests merged in 2020-07, with the labels that each got.

#37 Fixes/iac 99
  go.sum
  vmc/resource_vmc_sddc.go
  vmc/utils.go
Labels: bug, size/M

#48 Added check in resourceClusterRead to see if cluster exists and remove cluster information from terraform state file
  go.sum
  vmc/resource_vmc_cluster.go
  vmc/resource_vmc_site_recovery.go
  vmc/resource_vmc_srm_node.go
Labels: size/M

#52 Modified code to use connectorWrapper to resolve authentication error
  vmc/resource_vmc_sddc.go
Labels: size/XS
